### ISSUE TITLE
Actividad 4-Diseño de Objeto 3D

### ISSUE THREAD

**Issue by EdwinOrtiz1412** [SistemasTecTlaxiaco/actividad-4-diseno-de-objeto-3d-en-blender-equipo-irving-1#1]
[Actividad4 Diseño de Objeto.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-diseno-de-objeto-3d-en-blender-equipo-irving-1/files/14706033/Actividad4.Diseno.de.Objeto.pdf)

**Comment by josealfredo79** [comment]
Cual es la calificación...????

**Comment by magaly1311** [comment]
Calificacion 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
